spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/42feedback?characterEncoding=UTF-8
    username: root
    password: 1234

#    q
  profiles:
    include: oauth
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

42:
  user-code: 831e3446cad6d8322b48c77df90ce0353a9b7fca2c5a46358d1905686e98ce51
  client-id: 3dc76b7d4508c88aebe2386f0886f2cb8d858c5c64aa849442dbe4100794ced9
  client-secret: 6715a5b69e672988fbe0ae027994fe1d99f24d6ce4f99fb13714a9cb38e9856b
  redirect-uri: http://localhost:8080
  access-token: Bearer 88a210420bed7e7f2bb1dce8eacf360b5d3eb280e2491f1d5511062dd58107d1
server:
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force-response: true
    session:
      timeout: 30m
      cookie:
        domain: http://3.34.88.141/
        max-age: 30m
        http-only: true



